# Generated by Django 4.1 on 2023-08-23 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_nov_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nov',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/news', verbose_name='Превью новости'),
        ),
    ]
