# Generated by Django 4.1 on 2022-08-23 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_nov_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nov',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
