# Generated by Django 4.1 on 2022-08-23 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_nov_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nov',
            name='img',
            field=models.ImageField(null=True, upload_to='news/'),
        ),
    ]
