# Generated by Django 4.1 on 2022-08-23 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_nov_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nov',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='Дата публикации'),
        ),
    ]
