# Generated by Django 4.1 on 2022-08-23 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_nov_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nov',
            name='link_news',
            field=models.CharField(max_length=255, verbose_name='Ссылка'),
        ),
    ]
