# Generated by Django 4.1 on 2022-08-23 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_nov_link_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nov',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='Превью'),
        ),
    ]
