# Generated by Django 4.1 on 2022-08-27 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_nov_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, null=True, verbose_name='Имя пользователя')),
                ('email', models.CharField(max_length=150, null=True, verbose_name='Адрес электронной почты')),
                ('img', models.ImageField(blank=True, null=True, upload_to='avatar/', verbose_name='Аватарка')),
                ('first_name', models.CharField(max_length=150, null=True, verbose_name='Имя')),
                ('secondary_name', models.CharField(max_length=150, null=True, verbose_name='Фамилия')),
                ('date_register', models.DateField(auto_now_add=True, null=True, verbose_name='Дата регистрации')),
            ],
        ),
        migrations.AlterField(
            model_name='nov',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата публикации'),
        ),
    ]
