# Generated by Django 4.1 on 2022-08-27 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_account_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='username_a',
            field=models.CharField(max_length=150, null=True, verbose_name='Имя пользователя'),
        ),
    ]
