# Generated by Django 4.1 on 2022-08-28 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_account_first_name_account_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='first_name',
            new_name='first_name_a',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='last_name',
            new_name='last_name_a',
        ),
    ]
