# Generated by Django 4.1 on 2022-08-28 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_rename_first_name_account_first_name_a_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(blank=True, choices=[('Пользователь', 'Пользователь'), ('Спонсор', 'Спонсор'), ('Создатель', 'Создатель')], default='Пользователь', max_length=25, null=True, verbose_name='Роль пользователя'),
        ),
    ]
