# Generated by Django 4.1 on 2022-08-28 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_alter_account_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(blank=True, choices=[('Пользователь', 'Пользователь'), ('Спонсор', 'Спонсор'), ('Создатель', 'Создатель')], default='Пользователь', max_length=25, verbose_name='Роль пользователя'),
        ),
    ]
