# Generated by Django 4.1 on 2022-08-28 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_rename_first_name_a_account_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(blank=True, choices=[('Пользователь', 'Пользователь'), ('Спонсор', 'Спонсор'), ('Создатель', 'Создатель')], max_length=25, verbose_name='Роль пользователя'),
        ),
    ]
