# Generated by Django 4.1 on 2022-08-29 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_alter_account_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='pp_ua',
            field=models.BooleanField(default=False, verbose_name='Согласие на обработку данных и с пользовательским соглашением'),
        ),
    ]
