# Generated by Django 4.1 on 2022-08-29 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_account_pp_ua'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='pp_ua',
            field=models.BooleanField(verbose_name='Согласие на обработку данных и с пользовательским соглашением'),
        ),
    ]
