# Generated by Django 4.1 on 2022-08-29 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_alter_account_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='accept_ua_pp',
            field=models.BooleanField(null=True, verbose_name='Согласие со всеми правилами'),
        ),
        migrations.AddField(
            model_name='account',
            name='nick_in_credits',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Ник для титров'),
        ),
    ]
