# Generated by Django 4.1 on 2022-08-29 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_account_accept_ua_pp_account_nick_in_credits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='accept_ua_pp',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Согласие со всеми правилами'),
        ),
    ]
