# Generated by Django 4.1 on 2022-09-04 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_ip_remove_nov_views_news_nov_views'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ip',
            options={'verbose_name': 'Идентификатор устройства', 'verbose_name_plural': 'Идентификаторы устройств'},
        ),
        migrations.AddField(
            model_name='account',
            name='ip_address',
            field=models.CharField(blank=True, default='ABC', max_length=64, null=True, verbose_name='Ip'),
        ),
    ]
