# Generated by Django 4.1 on 2022-09-25 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_project_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_cost',
            name='date',
            field=models.DateField(verbose_name='Месяц'),
        ),
    ]
