# Generated by Django 4.1 on 2022-09-25 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_alter_project_cost_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название мода')),
                ('description', models.TextField(verbose_name='Описание')),
                ('author', models.CharField(max_length=255, verbose_name='Автор')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата публикации')),
                ('mod', models.FileField(blank=True, null=True, upload_to='game/modifications/', verbose_name='Модификация')),
            ],
            options={
                'verbose_name': 'Модификация',
                'verbose_name_plural': 'Модификации',
            },
        ),
        migrations.AlterField(
            model_name='nov',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img/news/', verbose_name='Превью'),
        ),
    ]
