# Generated by Django 4.1 on 2022-09-26 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0044_mod_alter_nov_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='mod',
            name='accept_mod',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Подтверждение'),
        ),
        migrations.AddField(
            model_name='mod',
            name='img_mod',
            field=models.ImageField(blank=True, null=True, upload_to='img/news/', verbose_name='Превью мода'),
        ),
    ]
