# Generated by Django 4.1 on 2022-10-21 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0045_mod_accept_mod_mod_img_mod'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project_cost',
        ),
        migrations.AlterField(
            model_name='mod',
            name='accept_mod',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Подтверждение'),
        ),
    ]
