# Generated by Django 4.1.1 on 2022-12-20 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0046_delete_project_cost_alter_mod_accept_mod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='img',
            field=models.ImageField(blank=True, default='img/avatar/standard_avatar.png', null=True, upload_to='img/avatar/', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='mod',
            name='img_mod',
            field=models.ImageField(blank=True, null=True, upload_to='img/mods/', verbose_name='Превью мода'),
        ),
    ]
