# Generated by Django 4.1.1 on 2023-02-12 12:01

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0047_alter_account_img_alter_mod_img_mod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='img',
            field=models.ImageField(blank=True, default='img/avatar/standard_avatar.png', null=True, upload_to=users.models.PathAndRename('img/avatar/'), verbose_name='Аватар'),
        ),
    ]
